version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:6
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
  api:
    container_name: api-container
    build: .
    restart: always
    image: survey-3-api
    ports:
      - "5050:5050"
    links:
      - mongo